### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ekko-zhao** [duanxinyuan/cipher-utils#4]
java: 无法访问com.dxy.library.exception.FormativeException
  错误的类文件: /Users/ekko/.m2/repository/com/github/duanxinyuan/exception-formative/1.0.0/exception-formative-1.0.0.jar!/com/dxy/library/exception/FormativeException.class类文件具有错误的版本 58.0, 应为 55.0
  请删除该文件或确保该文件位于正确的类路径子目录中。

作者大大可以帮忙解决下吗？谢谢

**Comment by duanxinyuan** [comment]
因为依赖的另一个jar是用的jdk15编译的…抱歉忘记改了，升级一下就好了
<dependency>
    <groupId>com.github.duanxinyuan</groupId>
    <artifactId>util-cipher</artifactId>
    <version>1.2.1</version>
</dependency>
